%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
#Camera1.fx: 517.306408
#Camera1.fy: 516.469215
#Camera1.cx: 318.643040
#Camera1.cy: 255.313989

#Camera1.k1: 0.262383
#Camera1.k2: -0.953104
#Camera1.p1: -0.005358
#Camera1.p2: 0.002628
#Camera1.k3: 1.163314

# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 644.6349487304688
Camera1.fy: 643.6536254882812
Camera1.cx: 637.49169921875
Camera1.cy: 361.69696044921875
Camera1.k1: -0.05639747902750969
Camera1.k2: 0.06732191890478134
Camera1.p1: -0.0003759726241696626
Camera1.p2: 0.0009479765431024134
Camera.width: 1280
Camera.height: 720

#Camera.width: 640
#Camera.height: 480

# Camera frames per second 
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.07732

# Depth map values factor
RGBD.DepthMapFactor: 5000.0 # 1.0 for ROS_bag

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

